apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: grafana
spec:
  type: {{ .Values.grafana.service.type }}
  ports:
    - port: {{ .Values.grafana.service.port }}
      targetPort: 3000
  selector:
    app: grafana
