replicaCount: 1

image:
  repository: grafana/grafana
  tag: latest
  pullPolicy: IfNotPresent

persistence:
  enabled: true
  size: 2Gi
  storageClassName: local-path


ingress:
  enabled: false
  path: /
  hosts:
    - grafana.local
  annotations: {}

dashboards:
  default:
    enabled: true

contactPoints:
  email-alert:
    email:
      to: 
        - "X-men555@list.ru" 
      from: "igor.simatic@gmail.com" 
      smarthost: "email-smtp.eu-north-1.amazonaws.com:587" 
      skip_verify: true 