---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: wordpress
spec:
  type:
    "{ .Values.wordpress.service.type }": null
  ports:
    - port:
        "{ .Values.wordpress.service.port }": null
      targetPort: 80
      nodePort: 32001
  selector:
    app: wordpress
