name: SSH Connection Example

on:
  push:
    branches:
      - task-5

jobs:
  deploy-wordpress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Очистка кеша SSH-конфигурации перед запуском
      - name: Clear SSH config cache
        run: |
          echo "Clearing SSH config cache..."
          rm -rf ~/.ssh/*

      # Пример использования кеширования для зависимостей
      - name: Cache SSH config
        uses: actions/cache@v2
        with:
          path: ~/.ssh
          key: ${{ runner.os }}-ssh-config-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-ssh-config-

      - name: Setup SSH connection and SOCKS5 Proxy
        env:
          K3S_SSH_PK: ${{ secrets.K3S_SSH_PK }}
          SSH_CONFIG: ${{ secrets.SSH_CONFIG }}
          K3S_IP: ${{ secrets.K3S_IP }}
          K3S_USER: ${{ secrets.K3S_USER }}
        run: |
          # Создаем директорию для SSH конфигурации
          mkdir -p ~/.ssh
          
          # Запускаем SSH-агент
          eval "$(ssh-agent -s)"
          
          # Устанавливаем правильные права доступа для приватного ключа
          echo "$K3S_SSH_PK" | tr -d '\r' > ~/.ssh/bastion_key
          chmod 600 ~/.ssh/bastion_key

          # Добавляем ключ в агент
          ssh-add ~/.ssh/bastion_key
          
          # Создаем SSH конфигурацию из секрета
          echo "$SSH_CONFIG" > ~/.ssh/config
          chmod 600 ~/.ssh/config

          # Добавляем сервер в known_hosts для предотвращения ошибки
          ssh-keyscan -H $K3S_IP >> ~/.ssh/known_hosts

          # Настройка туннеля для доступа к k3s API server
          ssh -L 6443:127.0.0.1:6443 -N -f $K3S_USER@$K3S_IP -o StrictHostKeyChecking=no

      # Добавление репозитория Bitnami и обновление репозиториев Helm
      - name: Add Bitnami Helm repository
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update

      # Проверка доступных версий MariaDB в репозитории Bitnami
      - name: Check available MariaDB versions
        run: |
          helm search repo bitnami/mariadb --versions

      # Обновление зависимостей Helm
      - name: Update Helm dependencies
        run: |
          helm dependency update helm-charts/wordpress

      - name: Deploy WordPress
        env:
          KUBECONFIG: /tmp/k3s.yml
        run: |
          # Записываем KUBECONFIG в файл и устанавливаем права
          echo "${{ vars.K3S_CONFIG }}" > $KUBECONFIG
          chmod 600 "$KUBECONFIG"

          # Проверка доступа к Kubernetes
          echo "Checking kubectl access..."
          kubectl version --client
          kubectl cluster-info
          kubectl get nodes

          # Деплой WordPress с помощью Helm
          kubectl get namespace wordpress || kubectl create namespace wordpress        
          helm upgrade --install wordpress -n wordpress helm-charts/wordpress
